package token

const (
	// SetMPContractURI ...
	SetMPContractURI = "/ddxf/dtoken/set_mp"
	// VerifyTokenURI ...
	VerifyTokenURI = "/ddxf/dtoken/verify"

	// UseTokenURI ...
	UseTokenURI = "/ddxf/dtoken/use"
	// UseTokenByAgentURI ...
	UseTokenByAgentURI = "/ddxf/dtoken/useTokenByAgent"

	// TransferTokenURI ...
	TransferTokenURI = "/ddxf/dtoken/transfer"

	// SetTokenAgentURI ...
	SetTokenAgentURI = "/ddxf/dtoken/set_agent"

	// AddTokenAgentURI ...
	AddTokenAgentURI = "/ddxf/dtoken/add_agent"

	// RemoveTokenAgentURI ...
	RemoveTokenAgentURI = "/ddxf/dtoken/remove_agent"

	// ClearTokenAgentURI ...
	ClearTokenAgentURI = "/ddxf/dtoken/clear_agent"

	// GetTokenURI ...
	GetTokenURI = "/ddxf/dtoken/get"

	// CreateTokenTemplateURI ...
	CreateTokenTemplateURI = "/ddxf/dtoken/create_template"

	// UpdateTokenTemplateURI ...
	UpdateTokenTemplateURI = "/ddxf/dtoken/update_template"

	// RemoveTokenTemplateURI ...
	RemoveTokenTemplateURI = "/ddxf/dtoken/remove_template"

	// GetTokenTemplateURI ...
	GetTokenTemplateURI = "/ddxf/dtoken/get_template"

	// SetTokenTemplateAuthURI ...
	SetTokenTemplateAuthURI = "/ddxf/dtoken/set_template_auth"

	// AddTokenTemplateAuthURI ...
	AddTokenTemplateAuthURI = "/ddxf/dtoken/add_template_auth"

	// RemoveTokenTemplateAuthURI ...
	RemoveTokenTemplateAuthURI = "/ddxf/dtoken/remove_template_auth"

	// ClearTokenTemplateAuthURI ...
	ClearTokenTemplateAuthURI = "/ddxf/dtoken/clear_template_auth"

	// GenerateTokenURI ...
	GenerateTokenURI = "/ddxf/dtoken/generate"
)
